# Generated by Django 3.2 on 2021-12-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
