# Generated by Django 3.2 on 2022-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20211229_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='length',
        ),
        migrations.AddField(
            model_name='film',
            name='image_horizontal',
            field=models.TextField(default=''),
        ),
    ]
